// Package main implements the molt documentation generator.
//
// It generates two VitePress markdown files that are derived from source:
//
//   - docs/reference/standard-library.md  — from builtins.ModuleDocs() in internal/builtins
//   - docs/examples.md  — from every .molt file under examples/
//
// Hand-written pages (getting-started, language-guide, architecture, editor-support)
// live directly in docs/ and are not touched by this tool.
//
// Usage:
//
//	go run ./cmd/docgen [project-root]
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"molt/internal/builtins"
)

func main() {
	root := "."
	if len(os.Args) > 1 {
		root = os.Args[1]
	}

	exDir := filepath.Join(root, "examples")
	outDir := filepath.Join(root, "docs")
	refDir := filepath.Join(outDir, "reference")

	fmt.Println("generating docs...")

	// Copy logo from assets/ into docs/public/ so VitePress picks it up.
	copyLogo(filepath.Join(root, "assets", "molt-logo.png"), filepath.Join(outDir, "public", "logo.png"))
	fmt.Println("  docs/public/logo.png")

	if err := os.MkdirAll(refDir, 0o755); err != nil {
		die("mkdir %s: %v", refDir, err)
	}

	writeFile(filepath.Join(refDir, "standard-library.md"), generateStandardLibrary())
	fmt.Println("  docs/reference/standard-library.md")

	examples := collectExamples(exDir)
	writeFile(filepath.Join(refDir, "examples.md"), generateExamples(examples))
	fmt.Println("  docs/reference/examples.md")

	fmt.Println("done.")
}

func copyLogo(src, dst string) {
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		die("mkdir %s: %v", filepath.Dir(dst), err)
	}
	data, err := os.ReadFile(src)
	if err != nil {
		die("read logo %s: %v", src, err)
	}
	if err := os.WriteFile(dst, data, 0o644); err != nil {
		die("write logo %s: %v", dst, err)
	}
}

// ── Standard library page ────────────────────────────────────────────────────

func generateStandardLibrary() string {
	var b strings.Builder

	b.WriteString("---\n")
	b.WriteString("# This file is auto-generated by cmd/docgen. Do not edit manually.\n")
	b.WriteString("# Source of truth: internal/builtins/*.go\n")
	b.WriteString("# Regenerate: go run ./cmd/docgen\n")
	b.WriteString("---\n\n")
	b.WriteString("# Standard Library\n\n")
	b.WriteString("Importable standard modules available to molt programs. ")
	b.WriteString("This page is generated from the source definitions in [`internal/builtins/`](https://github.com/OMouta/molt-lang/tree/main/internal/builtins).\n\n")

	b.WriteString("## Overview\n\n")
	b.WriteString("| Module | Summary |\n")
	b.WriteString("| --- | --- |\n")
	for _, module := range builtins.ModuleDocs() {
		anchor := anchorForModule(module.Path)
		b.WriteString(fmt.Sprintf("| [`%s`](#%s) | %s |\n", module.Path, anchor, module.Summary))
	}
	b.WriteString("\n")

	for _, module := range builtins.ModuleDocs() {
		b.WriteString(fmt.Sprintf("## %s\n\n", module.Path))
		b.WriteString(module.Summary + "\n\n")
		b.WriteString("```molt\n")
		b.WriteString(fmt.Sprintf("import %q\n", module.Path))
		b.WriteString("```\n\n")
		for _, doc := range module.Symbols {
			name := funcName(doc.Signatures[0])
			b.WriteString(fmt.Sprintf("### %s\n\n", name))
			for _, sig := range doc.Signatures {
				b.WriteString("```molt\n")
				b.WriteString(sig + "\n")
				b.WriteString("```\n\n")
			}
			b.WriteString(doc.Summary + "\n\n")
			if doc.Detail != "" {
				b.WriteString(doc.Detail + "\n\n")
			}
		}
	}

	return b.String()
}

func anchorForModule(path string) string {
	return strings.ToLower(strings.ReplaceAll(path, ":", ""))
}

// funcName extracts the function name from a signature like "eval(code)" → "eval".
func funcName(sig string) string {
	if i := strings.Index(sig, "("); i >= 0 {
		return sig[:i]
	}
	return sig
}

// ── Examples page ─────────────────────────────────────────────────────────────

type example struct {
	Name     string // filename without .molt
	Category string // parent directory name
	Code     string // file contents
	Comment  string // text of first # comment, if any
}

func collectExamples(dir string) []example {
	entries, err := os.ReadDir(dir)
	if err != nil {
		die("read examples dir %s: %v", dir, err)
	}

	var out []example
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		cat := entry.Name()
		files, err := os.ReadDir(filepath.Join(dir, cat))
		if err != nil {
			continue
		}
		for _, f := range files {
			if !strings.HasSuffix(f.Name(), ".molt") {
				continue
			}
			code, err := os.ReadFile(filepath.Join(dir, cat, f.Name()))
			if err != nil {
				continue
			}
			out = append(out, example{
				Name:     strings.TrimSuffix(f.Name(), ".molt"),
				Category: cat,
				Code:     string(code),
				Comment:  firstComment(string(code)),
			})
		}
	}
	return out
}

func firstComment(code string) string {
	for _, line := range strings.SplitN(code, "\n", 10) {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		if strings.HasPrefix(line, "# ") {
			return strings.TrimPrefix(line, "# ")
		}
		return ""
	}
	return ""
}

func catTitle(cat string) string {
	known := map[string]string{
		"basic":         "Basic",
		"errors":        "Error Handling",
		"loops":         "Loops",
		"import_export": "Imports & Exports",
		"others":        "Other Examples",
	}
	if t, ok := known[cat]; ok {
		return t
	}
	return toTitleCase(cat)
}

func toTitleCase(s string) string {
	words := strings.Split(s, "_")
	for i, w := range words {
		if len(w) > 0 {
			words[i] = strings.ToUpper(w[:1]) + w[1:]
		}
	}
	return strings.Join(words, " ")
}

func generateExamples(examples []example) string {
	// Group by category, then sort by priority.
	type group struct {
		Name     string
		Examples []example
	}
	groupMap := map[string]*group{}
	var order []string
	for _, ex := range examples {
		if _, ok := groupMap[ex.Category]; !ok {
			groupMap[ex.Category] = &group{Name: ex.Category}
			order = append(order, ex.Category)
		}
		groupMap[ex.Category].Examples = append(groupMap[ex.Category].Examples, ex)
	}
	priority := map[string]int{"basic": 0, "loops": 1, "errors": 2, "import_export": 3, "others": 4}
	sort.Slice(order, func(i, j int) bool {
		pi, pj := priority[order[i]], priority[order[j]]
		if pi != pj {
			return pi < pj
		}
		return order[i] < order[j]
	})

	var b strings.Builder

	b.WriteString("---\n")
	b.WriteString("# This file is auto-generated by cmd/docgen. Do not edit manually.\n")
	b.WriteString("# Source: examples/ directory\n")
	b.WriteString("# Regenerate: go run ./cmd/docgen\n")
	b.WriteString("---\n\n")
	b.WriteString("# Examples\n\n")
	b.WriteString("Runnable example programs demonstrating molt features. ")
	b.WriteString("Source files live in the [`examples/`](https://github.com/OMouta/molt-lang/tree/main/examples) directory.\n\n")

	for _, cat := range order {
		g := groupMap[cat]
		b.WriteString(fmt.Sprintf("## %s\n\n", catTitle(cat)))
		for _, ex := range g.Examples {
			path := ex.Category + "/" + ex.Name + ".molt"
			b.WriteString(fmt.Sprintf("### %s\n\n", toTitleCase(ex.Name)))
			if ex.Comment != "" {
				b.WriteString(ex.Comment + "\n\n")
			}
			b.WriteString(fmt.Sprintf("::: details `%s`\n\n", path))
			b.WriteString("```\n")
			b.WriteString(strings.TrimRight(ex.Code, "\n"))
			b.WriteString("\n```\n\n")
			b.WriteString(":::\n\n")
		}
	}

	return b.String()
}

// ── Utilities ─────────────────────────────────────────────────────────────────

func writeFile(path, content string) {
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		die("write %s: %v", path, err)
	}
}

func die(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "docgen: "+format+"\n", args...)
	os.Exit(1)
}
